# Generated by Django 4.2.4 on 2025-09-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
