# Generated by Django 4.2.4 on 2025-09-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla', '0002_subject_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
