# Generated by Django 4.2.4 on 2025-09-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla', '0003_subject_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ingeniería Informática', help_text='Nombre de la carrera', max_length=200)),
                ('university', models.CharField(default='Colegio Mayor del Cauca', help_text='Nombre de la universidad', max_length=200)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
    ]
