# Generated by Django 5.2.6 on 2025-09-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla', '0004_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del estudiante', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
