# Generated by Django 5.2.6 on 2025-09-23 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la carrera', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='career',
            field=models.ForeignKey(blank=True, help_text='Carrera del estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='malla.career'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(help_text='Nombre de la carrera', max_length=200),
        ),
        migrations.AlterField(
            model_name='career',
            name='university',
            field=models.CharField(help_text='Nombre de la universidad', max_length=200),
        ),
    ]
