# Generated by Django 5.2.6 on 2025-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla', '0006_career_created_at_student_career_alter_career_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.PositiveIntegerField(blank=True, help_text='Semestre actual del estudiante', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_login_completed',
            field=models.BooleanField(default=False, help_text='Indica si el estudiante ha completado la configuración inicial'),
        ),
    ]
